includes:
- nested.yaml

templates:
  each:
    powershell: |
      (@() + $each.items) | ForEach-Object { Invoke-Expression $each.action }
  steps:
    each:
      items: $[[$_.steps]]
      action: $_ | Invoke-Step
