name: Tests

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@develop
    - name: Run tests
      run: pwsh -File .\pwshake.ps1
