name: all tests

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Run tests
      run: pwsh -NoLogo -NoProfile -File ./tests/pwshake.Tests.ps1
