name: Tests

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@develop
    - name: Run tests
      run: powershell -File .\pwshake.ps1
