name: all tests

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Run tests
      run: ./pwshake.ps1
      shell: pwsh
